version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=comercioDB
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password12345
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=C10searchengine
    ports:
      - "5050:80"
    depends_on:
      - 'postgres'
